# Generated by Django 3.1 on 2020-09-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condidat',
            name='availablity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='condidat',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='condidat',
            name='e_mail',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='condidat',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='condidat',
            name='phone_numbr',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='condidat',
            name='cv',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
