# Generated by Django 3.0.3 on 2020-09-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200905_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='condidat',
            name='expirience_years_nbr',
            field=models.IntegerField(null=True),
        ),
    ]
