# Generated by Django 3.1 on 2020-09-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_condidat_expirience_years_nbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='condidat',
            name='confirmation',
            field=models.CharField(default='e', max_length=1),
        ),
    ]
